### ISSUE TITLE
Bug: Preview doesn't open

### ISSUE THREAD

**Issue by evgeniyworkbel** [guesswhozzz/021011.zsh-theme#10]

**Comment by guesswhozzz** [comment]
> _No description provided._

Where exactly does the preview not open? In the readme?

**Comment by egorlem** [comment]
@evgeniyworkbel Where exactly does the preview not open? In the readme?

**Comment by evgeniyworkbel** [comment]
> @evgeniyworkbel Where exactly does the preview not open? In the readme?

yes
